- hosts: localhost

  vars:
    swap_file_size_mb: '2048'
    security_ssh_password_authentication: "yes"
    security_ssh_permit_root_login: "yes"
    security_ssh_port: 22
  pre_tasks:
    - name: Set node_exporter_arch to armv7 if architecture is aarch64
      set_fact:
        node_exporter_arch: armv7
      when: ansible_architecture == "aarch64"
  roles:
    - geerlingguy.swap
    - geerlingguy.security
    - geerlingguy.node_exporter
    - geerlingguy.docker
    - role: artis3n.tailscale
      vars:
        tailscale_up_skip: true
    - geerlingguy.helm