- hosts: localhost
  tasks:
    - name: Add ingress-nginx chart repo
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Add cert-manager chart repo
      kubernetes.core.helm_repository:
        name: cert-manager
        repo_url: "https://charts.jetstack.io"
       
    - name: Add cert-manager-issuers-letsencrypt chart repo
      kubernetes.core.helm_repository:
        name: cert-manager-issuers-letsencrypt
        repo_url: "https://rubenv.github.io/helm-cert-manager-issuers-letsencrypt"

    - name: Deploy Ingress Nginx
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress
        create_namespace: true
        values:
          controller:
            extraArgs:
              update-status: "true"
    - name: Deploy cert manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: cert-manager/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        values:
          crds:
            enabled: true

    - name: Deploy cert manager letsencrypt issuer
      kubernetes.core.helm:
        name: cert-manager-issuers-letsencrypt
        chart_ref: cert-manager-issuers-letsencrypt/cert-manager-issuers-letsencrypt
        release_namespace: cert-manager
        create_namespace: true
        values:
          email: "{{ letsencrypt_email }}"